#!/bin/sh
echo 'Compiling Utilities' 
g++  -std=c++2a -c utilities.cpp -o bin/build/utilities.o
echo 'Compiling NEAT' 
g++  -std=c++2a -fopenmp -c neat.cpp -o bin/build/neat.o
echo 'Compiling Joiner'
g++  -std=c++2a -o runNEAT bin/build/neat.o bin/build/utilities.o -lgomp
./runNEAT   